export default {
  theme: {
    light: {
      colors: {
        primary: "#FFFFFF",
        secondary: "#F2F2F7",
        secondaryLight: "#F8F9FE",
        textPrimary: "#11263C",
        textSecondary: "#D0D1D2",
        purple: "#422F8A",
        mediumPurple: "#7459D9",
        lightPurple: "#7459D933",
        border: "#ECE9F1",
      },
      fontSizes: {
        xxs: "0.5rem",
        xs: "0.7rem",
        sm: "0.85rem",
        md: "1rem",
        lg: "1.2rem",
        xl: "1.44rem",
        "2xl": "2rem",
        "3xl": "2.5rem",
        "4xl": "3.6rem",
        "5xl": "5rem",
      },
    },

    dark: {
      colors: {
        primary: "#2C2C2E",
        secondary: "#1C1C1E",
        secondaryLight: "#3A3A3C",
        textPrimary: "#ffffff",
        textSecondary: "#EBEBF599",
        purple: "#5E5CE6",
        mediumPurple: "#5E5CE6",
        lightPurple: "#5E5CE640",
        border: "#3D3C41",
      },
      fontSizes: {
        xxs: "0.5rem",
        xs: "0.7rem",
        sm: "0.85rem",
        md: "1rem",
        lg: "1.2rem",
        xl: "1.44rem",
        "2xl": "2rem",
        "3xl": "2.5rem",
        "4xl": "3.6rem",
        "5xl": "5rem",
      },
    },
  },
};
